"""empty message

Revision ID: 9fb652969211
Revises: 
Create Date: 2019-04-15 12:37:58.233453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb652969211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet',
    sa.Column('sheet_label', sa.String(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('avgmoe', sa.DECIMAL(), nullable=True),
    sa.Column('avgsg', sa.DECIMAL(), nullable=True),
    sa.Column('avgmc', sa.DECIMAL(), nullable=True),
    sa.Column('avgvel', sa.DECIMAL(), nullable=True),
    sa.Column('avgupt', sa.DECIMAL(), nullable=True),
    sa.Column('pkdensity', sa.DECIMAL(), nullable=True),
    sa.Column('effvel', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('lvel', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('rvel', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('lupt', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('rupt', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('sg', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.Column('mc', sa.ARRAY(sa.DECIMAL()), nullable=True),
    sa.PrimaryKeyConstraint('sheet_label'),
    sa.UniqueConstraint('iteration')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet')
    # ### end Alembic commands ###
